### ISSUE TITLE
undefined: DefaultDevice when I try to run the scanner

### ISSUE THREAD

**Issue by howardgrams** [Seitanas/wosensortho-exporter#4]
I know nothing about go, but I downloaded and installed go,   and when I run go version it reports go version go1.21.6 windows/amd64

But when I try to run the scanner I get 
T:\wosensortho-exporter-master>go run cmd/scanner/main.go
# github.com/go-ble/ble/examples/lib/dev
C:\Users\howar\go\pkg\mod\github.com\go-ble\ble@v0.0.0-20230130210458-dd4b07d15402\examples\lib\dev\dev.go:9:9: undefined: DefaultDevice

What am I missing?  I'd REALLY love to be able to get data from my SwitchBot Indoor/Outdoor Thermo-Hygrometer into Windows!

**Comment by Seitanas** [comment]
Hello,
exporter uses go-ble library which is designed to run on Linux and Macs only. So its not something you could do to fix this.
